### ISSUE TITLE
Add a LICENSE file?

### ISSUE THREAD

**Issue by spicyjack** [Stuart-Clark192/MOS6502#1]
Hi,

Thanks for putting this project out there.  I have been learning a lot by going through it and seeing how you've implemented a 6502.  Having the playground support and the detailed SwiftUI implementation to look at is nice as well.

Would it be possible for you to add a license to this project, so that people who find your project in the future know how they can use/reuse it?

Thanks!

**Comment by Stuart-Clark192** [comment]
Hey, 

Thank you so much for the feedback, there are a few things I would like to finish and tidy up in this but I will take a look at adding license file as soon as I can.

Any comments or suggestions are welcome.

Kind Regards

Stuart

**Comment by spicyjack** [comment]
> Thank you so much for the feedback, there are a few things I would like to finish and tidy up in this but I will take a look at adding license file as soon as I can.

Excellent, thanks.
 
> Any comments or suggestions are welcome.

I hesitate in giving suggestions before learning about what your goal(s) for this project is/are.  I guess my first suggestion would be to add some info about the project to the README.  I'd be more than happy to add things to the README like how to run the Playbook in Xcode for example; this might help encourage people who are new to Xcode and it's ecosystem to download and play around with this project.

One suggestion I can give if you are looking to check the CPU and related classes for "correct" 6502 behaviour, have you seen the 6502 Functional Tests project (https://github.com/Klaus2m5/6502_65C02_functional_tests)?

Thanks!

**Comment by Stuart-Clark192** [comment]
Hi, 

Sorry for the delay in getting back to you, ben a busy few weeks unfortunately with other projects, will try and get some time to update this properly, I would be more than happy if you have stuff you would like to contribute to the Readme file.

Going forwards when I can get some more time to get back to this properly, I still need to fix the "SBC" commands as they do not currently work correctly, then I need to make it cycle accurate :)
